version: '3.7'
services:
    redis-main:
        image: redis:alpine
        ports:
            - ${REDIS_PORT}:6379
        command: redis-server --requirepass ${REDIS_PASS} --bind 0.0.0.0 --protected-mode no
        networks:
            kiora_net:
                ipv4_address: 172.22.0.4
        restart: always

    redis-replicat:
        image: redis:alpine
        command: redis-server --masterauth ${REDIS_PASS} --slaveof 172.22.0.4 6379
        links:
            - redis-main
        networks:
            - kiora_net
        restart: always

    redis-sentinel:
        image: redis
        command: >
            bash -c "echo 'port 26379' > sentinel.conf &&
            echo 'dir /tmp' >> sentinel.conf &&
            echo 'sentinel monitor primary 172.22.0.4 6379 2' >> sentinel.conf &&
            echo 'sentinel down-after-milliseconds primary 5000' >> sentinel.conf &&
            echo 'sentinel parallel-syncs primary 1' >> sentinel.conf &&
            echo 'sentinel failover-timeout primary 5000' >> sentinel.conf &&
            cat sentinel.conf &&
            redis-server sentinel.conf --sentinel"
        links:
            - redis-main
            - redis-replicat
        networks:
            - kiora_net
        restart: always
    db:
        image: mysql
        command: ["--default-authentication-plugin=mysql_native_password"]
        ports:
            - ${DB_PORT}:3306
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: ${DB_NAME}
            MYSQL_USER: symfony
            MYSQL_PASSWORD: symfony
        volumes:
          - db-volume:/var/lib/mysql
        networks:
            - kiora_net
        restart: always
    blackfire:
        image: blackfire/blackfire
        ports: ["8707"]
        environment:
            BLACKFIRE_LOG_LEVEL: 4
            BLACKFIRE_SERVER_ID: ${BLACKFIRE_SERVER_ID}
            BLACKFIRE_SERVER_TOKEN: ${BLACKFIRE_SERVER_TOKEN}
            BLACKFIRE_CLIENT_ID: ${BLACKFIRE_CLIENT_ID}
            BLACKFIRE_CLIENT_TOKEN: ${BLACKFIRE_CLIENT_TOKEN}
        volumes:
            - ./hosts:/etc/hosts
        networks:
            - kiora_net
    nginx:
        image: kiora/nginx:sf4-3
        ports:
            - ${NGNIX_PORT}:80
            - 443:443
        depends_on:
            - tools
        volumes:
            - ${DOCKER_VOLUME_PATH}:/var/www
            - ./hosts:/etc/hosts
            - ./symfony.conf:/etc/nginx/conf.d/symfony.conf
            - ./clients/nginx/${CLIENT}.conf:/etc/nginx/conf.d/${CLIENT}.conf
            - ./upstream.conf:/etc/nginx/conf.d/upstream.conf
            - ./_wildcard.localhost.pem:/etc/ssl/mkcert/_wildcard.localhost.pem
            - ./_wildcard.localhost-key.pem:/etc/ssl/mkcert/_wildcard.localhost-key.pem
        networks:
            - kiora_net
        restart: always

    tools:
        image: kiora/tools:latest
        ports:
            - ${SSH_PORT}:22
            - 3000:3000
        environment:
            - GIT_NAME=${GIT_NAME}
            - GIT_EMAIL=${GIT_EMAIL}
            - GIT_HOST=${GIT_HOST}
            - GIT_IP=${GIT_IP}
        depends_on:
            - db
            - redis-main
        volumes:
            - ${DOCKER_VOLUME_PATH}:/var/www
            - ${DOCKER_VOLUME_CONFIG}:/home/kiora/.ssh
            - ./hosts:/etc/hosts
            - /tmp:/tmp
            - ./php.ini:/usr/local/etc/php/conf.d/php.ini
        networks:
            - kiora_net
        restart: always


networks:
    kiora_net:
        driver: bridge
        ipam:
            config:
                - subnet: 172.22.0.0/24

volumes:
    data-volume:
    db-volume:
    config-volume:
