version: '3.7'
services:
    db:
        image: mysql
        command: ["--default-authentication-plugin=mysql_native_password"]
        ports:
            - ${DB_PORT}:3306
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: ${DB_NAME}
            MYSQL_USER: symfony
            MYSQL_PASSWORD: symfony
        volumes:
          - db-volume:/var/lib/mysql
        networks:
            kiora_net:
                ipv4_address: 172.22.0.2
        restart: always

    redis:
        image: redis:alpine
        ports:
            - ${REDIS_PORT}:6379
        networks:
            kiora_net:
                ipv4_address: 172.22.0.4
        restart: always

    php:
        image: kiora/php:latest
        ports:
            - ${PHP_PORT}:9000
        volumes:
            - ${DOCKER_VOLUME_PATH}:/var/www
            - ./hosts:/etc/hosts
            - /tmp:/tmp
        depends_on:
            - db
            - redis
        networks:
            kiora_net:
                ipv4_address: 172.22.0.6
        restart: always
    nginx:
        image: kiora/nginx:sf4-3
        ports:
            - ${NGNIX_PORT}:80
            - 443:443
        depends_on:
            - php
        volumes:
            - ${DOCKER_VOLUME_PATH}:/var/www
            - ./hosts:/etc/hosts
            - ./symfony.conf:/etc/nginx/conf.d/symfony.conf
            - ./_wildcard.localhost.pem:/etc/ssl/mkcert/_wildcard.localhost.pem
            - ./_wildcard.localhost-key.pem:/etc/ssl/mkcert/_wildcard.localhost-key.pem
        networks:
            kiora_net:
                ipv4_address: 172.22.0.8
        restart: always

    tools:
        image: kiora/tools:latest
        ports:
            - ${SSH_PORT}:22
            - 8080:8080
            - 3000:3000
        environment:
            - GIT_NAME=${GIT_NAME}
            - GIT_EMAIL=${GIT_EMAIL}
            - GIT_HOST=${GIT_HOST}
            - GIT_IP=${GIT_IP}
        depends_on:
            - php
        volumes:
            - ${DOCKER_VOLUME_PATH}:/var/www
            - ${DOCKER_VOLUME_CONFIG}:/home/kiora/.ssh
            - ./hosts:/etc/hosts
            - /tmp:/tmp
            - ./php.ini:/usr/local/etc/php/conf.d/php.ini
        networks:
            kiora_net:
                ipv4_address: 172.22.0.10
        restart: always


networks:
    kiora_net:
        driver: bridge
        ipam:
            config:
                - subnet: 172.22.0.0/24

volumes:
    data-volume:
    db-volume:
    config-volume:
